sudo: required
services:
  - docker

before_install:
# {{docker username}}/{{repo name}}
  - docker build -t chrisocal/docker-react -f Dockerfile.dev .

script:
  - docker run chrisocal/docker-react npm run test -- --coverage